name: Build and Publish Docker Container

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build and push Docker container
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        docker buildx create --use
        docker login docker.pkg.github.com -u $DOCKER_USERNAME -p $DOCKER_PASSWORD
        docker buildx build --platform linux/amd64 -t docker.pkg.github.com/votre-utilisateur/nom-de-votre-image:latest .
        docker push docker.pkg.github.com/votre-utilisateur/nom-de-votre-image:latest
