name: docker.pkg.github.com/med0104/docker-image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker container
      run: docker buildx build --platform linux/amd64 -t docker.pkg.github.com/votre-utilisateur/nom-de-votre-image:latest .

    - name: Log in to GitHub Packages
      run: echo ${{ secrets.GITHUB_TOKEN }} | docker login docker.pkg.github.com -u ${{ github.repository_owner }} --password-stdin

    - name: Push Docker container to GitHub Packages
      run: docker push docker.pkg.github.com/votre-utilisateur/nom-de-votre-image:latest

