name: build-and-publish-docker-container

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: build-and-publish-docker-container
      env:
        DOCKER_USERNAME: ${{ secrets.ADDRESE }}
        DOCKER_PASSWORD: ${{ secrets.MDP }}
      run: |
        docker buildx create --use
        docker login docker.pkg.github.com -u secrets.ADDRESE -p secrets.MDP
        docker buildx build --platform linux/amd64 -t github.com/med0104/ue19_labo09-10 --push .
        docker push github.com/med0104/ue19_labo09-10:latest
